### PR TITLE
Mockingbird: Results submission: Initial revision.

### PR DESCRIPTION
**Pull request by agutkin**
This is an **initial** revision that *only* contains the actual results on the surprise data.

This change includes the results for the three systems: `i1`, `n1` and `n2`. These are neural models:

1.  System `i1` provides the results for all five data partitions. The final result `i1/surprise/${LG}/${PART}` is generated by the ensemble of 10 individual systems under `i1/surprise/bantubvd/${PART}/_${N}/`, where `${LG}` is the language group, `${PART}` the partition and `${N}` is an integer from 1 to 10.
1.  System `n1` provides the results for all five data partitions. For each partition and language we provide results on the surprise data generated by the model at three time steps: 25K steps, 35K steps and 100K steps. 
1.  System `n2` only provides the results for 10% scarcity data partition.

More details on the above systems to follow.

Systems' implementation is [here](https://github.com/google-research/google-research/tree/master/cognate_inpaint_neighbors).

Authors: @rwsproat, @ckirov, @agutkin

### CODE REVIEW

**Review by LinguList — CHANGES_REQUESTED** [review]
Thanks a lot. Having the results is perfect at this stage of the analysis. 

I did not really think about the possibility to submit more than one system, but this is of course possible. Yet we have to think how to handle the resulting repository structure.

What I would like to suggest is the following: 

Instead of providing your team name and then a system as a nested folder, can I ask you to make three folders for each system? You'd then call them `mockingbird-i1`, `mockingbird-n1`, and `mockingbird-n2`. I'd even be inclined to ask you to sub-divide the `n1`-results further into three packages, given the number of runs, you could call them `n1-a`, `n1-b`, `n1-c`, or give them the number of runs (25000, 35000, 100000). 

There are two major advantages of this:

1. when comparing systems, team Mockingbird sends different cars into the race, and they compete individually with the other cars send out by different teams
2. to evaluate and compare all methods with each other, we can just register the folders and directly search for the results, and we don't need to make custom adjustments to go deeper inside a folder to get the files (as I'd have to do now for `n1`).

So may I ask you to re-arrange the folder structure with the results, so that we do not need to use custom paths to analyse the three (or rather 5, with a, b, c for n1) systems explicitly? 

Sorry we haven't foreseen this situation earlier.
4.

**Comment by agutkin** [comment]
> Thanks a lot. Having the results is perfect at this stage of the analysis.
> 
> I did not really think about the possibility to submit more than one system, but this is of course possible. Yet we have to think how to handle the resulting repository structure.
> 
> What I would like to suggest is the following:
> 
> Instead of providing your team name and then a system as a nested folder, can I ask you to make three folders for each system? You'd then call them `mockingbird-i1`, `mockingbird-n1`, and `mockingbird-n2`. I'd even be inclined to ask you to sub-divide the `n1`-results further into three packages, given the number of runs, you could call them `n1-a`, `n1-b`, `n1-c`, or give them the number of runs (25000, 35000, 100000).
> 
> There are two major advantages of this:
> 
> 1. when comparing systems, team Mockingbird sends different cars into the race, and they compete individually with the other cars send out by different teams
> 2. to evaluate and compare all methods with each other, we can just register the folders and directly search for the results, and we don't need to make custom adjustments to go deeper inside a folder to get the files (as I'd have to do now for `n1`).
> 
> So may I ask you to re-arrange the folder structure with the results, so that we do not need to use custom paths to analyse the three (or rather 5, with a, b, c for n1) systems explicitly?
> 
> Sorry we haven't foreseen this situation earlier. 4.

Thanks, Mattis. This definitely makes sense (as long as we don't have to write five papers :)).  I'll re-arrange the folders per your request and ping this thread when done.

**Comment by LinguList** [comment]
Super! Of course, only one paper needs to be written. But in the summary, we'll then be able to rank all your five methods with the other methods, so I consider this as very nice.

**Comment by agutkin** [comment]
> Super! Of course, only one paper needs to be written. But in the summary, we'll then be able to rank all your five methods with the other methods, so I consider this as very nice.

Using the car metaphor, I've rearranged the results into five systems: mockingbird-i1 (Trabi), mockingbird-n1-{a,b,c} (variants of Wartburg) and  mockingbird-n2 (Yugo).

**Comment by LinguList** [comment]
Very nice, I'll merge this, many thanks!

**Review by LinguList — APPROVED** [review]

**Pull request merged**
